upgrade to node-v7.7.1

diff --git a/node/Makefile b/node/Makefile
--- a/node/Makefile
+++ b/node/Makefile
@@ -10,6 +10,8 @@ TEST_CI_ARGS ?=
 STAGINGSERVER ?= node-www
 LOGLEVEL ?= silent
 OSTYPE := $(shell uname -s | tr '[A-Z]' '[a-z]')
+COVTESTS ?= test
+GTEST_FILTER ?= "*"
 
 ifdef JOBS
   PARALLEL_ARGS = -j $(JOBS)
@@ -113,8 +115,77 @@ distclean:
 
 check: test
 
+# Remove files generated by running coverage, put the non-instrumented lib back
+# in place
+coverage-clean:
+	if [ -d lib_ ]; then rm -rf lib; mv lib_ lib; fi
+	-rm -rf node_modules
+	-rm -rf gcovr testing
+	-rm -rf out/$(BUILDTYPE)/.coverage
+	-rm -rf .cov_tmp coverage
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/*.gcda
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/tracing/*.gcda
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/*.gcno
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/tracing*.gcno
+
+# Build and test with code coverage reporting.  Leave the lib directory
+# instrumented for any additional runs the user may want to make.
+# For C++ coverage reporting, this needs to be run in conjunction with configure
+#  --coverage.  html coverage reports will be created under coverage/
+
+coverage: coverage-test
+
+coverage-build: all
+	mkdir -p node_modules
+	if [ ! -d node_modules/istanbul-merge ]; then \
+		$(NODE) ./deps/npm install istanbul-merge; fi
+	if [ ! -d node_modules/nyc ]; then $(NODE) ./deps/npm install nyc; fi
+	if [ ! -d gcovr ]; then git clone --depth=1 \
+		--single-branch git://github.com/gcovr/gcovr.git; fi
+	if [ ! -d testing ]; then git clone --depth=1 \
+		--single-branch https://github.com/nodejs/testing.git; fi
+	if [ ! -f gcovr/scripts/gcovr.orig ]; then \
+		(cd gcovr && patch -N -p1 < \
+		"$(CURDIR)/testing/coverage/gcovr-patches.diff"); fi
+	if [ -d lib_ ]; then rm -rf lib; mv lib_ lib; fi
+	mv lib lib_
+	$(NODE) ./node_modules/.bin/nyc instrument lib_/ lib/
+	$(MAKE)
+
+coverage-test: coverage-build
+	-rm -rf out/$(BUILDTYPE)/.coverage
+	-rm -rf .cov_tmp
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/*.gcda
+	-rm -f out/$(BUILDTYPE)/obj.target/node/src/tracing/*.gcda
+	-$(MAKE) $(COVTESTS)
+	mv lib lib__
+	mv lib_ lib
+	mkdir -p coverage .cov_tmp
+	$(NODE) ./node_modules/.bin/istanbul-merge --out \
+		.cov_tmp/libcov.json 'out/Release/.coverage/coverage-*.json'
+	(cd lib && .$(NODE) ../node_modules/.bin/nyc report \
+		--temp-directory "$(CURDIR)/.cov_tmp" -r html \
+		--report-dir "../coverage")
+	-(cd out && "../gcovr/scripts/gcovr" --gcov-exclude='.*deps' \
+		--gcov-exclude='.*usr' -v -r Release/obj.target/node \
+		--html --html-detail -o ../coverage/cxxcoverage.html)
+	mv lib lib_
+	mv lib__ lib
+	@echo -n "Javascript coverage %: "
+	@grep -B1 Lines coverage/index.html | head -n1 \
+		| sed 's/<[^>]*>//g'| sed 's/ //g'
+	@echo -n "C++ coverage %: "
+	@grep -A3 Lines coverage/cxxcoverage.html | grep style  \
+		| sed 's/<[^>]*>//g'| sed 's/ //g'
+
 cctest: all
-	@out/$(BUILDTYPE)/$@
+	@out/$(BUILDTYPE)/$@ --gtest_filter=$(GTEST_FILTER)
+
+list-gtests:
+ifeq (,$(wildcard out/$(BUILDTYPE)/cctest))
+	$(error Please run 'make cctest' first)
+endif
+	@out/$(BUILDTYPE)/cctest --gtest_list_tests
 
 v8:
 	tools/make-v8.sh
@@ -133,8 +204,10 @@ test-parallel: all
 test-valgrind: all
 	$(PYTHON) tools/test.py --mode=release --valgrind sequential parallel message
 
-test/gc/build/Release/binding.node: \
-	$(NODE_EXE) test/gc/binding.cc test/gc/binding.gyp
+# Implicitly depends on $(NODE_EXE).  We don't depend on it explicitly because
+# it always triggers a rebuild due to it being a .PHONY rule.  See the comment
+# near the build-addons rule for more background.
+test/gc/build/Release/binding.node: test/gc/binding.cc test/gc/binding.gyp
 	$(NODE) deps/npm/node_modules/node-gyp/bin/node-gyp rebuild \
 		--python="$(PYTHON)" \
 		--directory="$(shell pwd)/test/gc" \
@@ -172,7 +245,7 @@ test/addons/.buildstamp: config.gypi \
 #	Cannot use $(wildcard test/addons/*/) here, it's evaluated before
 #	embedded addons have been generated from the documentation.
 	@for dirname in test/addons/*/; do \
-		echo "\nBuilding addon $$PWD/$$dirname" ; \
+		printf "\nBuilding addon $$PWD/$$dirname\n" ; \
 		env MAKEFLAGS="-j1" $(NODE) deps/npm/node_modules/node-gyp/bin/node-gyp \
 		        --loglevel=$(LOGLEVEL) rebuild \
 			--python="$(PYTHON)" \
@@ -224,6 +297,11 @@ test-ci-js: | clear-stalled
 	$(PYTHON) tools/test.py $(PARALLEL_ARGS) -p tap --logfile test.tap \
 		--mode=release --flaky-tests=$(FLAKY_TESTS) \
 		$(TEST_CI_ARGS) $(CI_JS_SUITES)
+	# Clean up any leftover processes
+	PS_OUT=`ps awwx | grep Release/node | grep -v grep | awk '{print $$1}'`; \
+	if [ "$${PS_OUT}" ]; then \
+		echo $${PS_OUT} | $(XARGS) kill; exit 1; \
+	fi
 
 test-ci: LOGLEVEL := info
 test-ci: | clear-stalled build-addons
@@ -231,6 +309,11 @@ test-ci: | clear-stalled build-addons
 	$(PYTHON) tools/test.py $(PARALLEL_ARGS) -p tap --logfile test.tap \
 		--mode=release --flaky-tests=$(FLAKY_TESTS) \
 		$(TEST_CI_ARGS) $(CI_NATIVE_SUITES) $(CI_JS_SUITES)
+	# Clean up any leftover processes
+	PS_OUT=`ps awwx | grep Release/node | grep -v grep | awk '{print $$1}'`; \
+	if [ "$${PS_OUT}" ]; then \
+		echo $${PS_OUT} | $(XARGS) kill; exit 1; \
+	fi
 
 test-release: test-build
 	$(PYTHON) tools/test.py --mode=release
@@ -274,6 +357,11 @@ test-npm-publish: $(NODE_EXE)
 
 test-addons: test-build
 	$(PYTHON) tools/test.py --mode=release addons
+
+test-addons-clean:
+	$(RM) -rf test/addons/??_*/
+	$(RM) -rf test/addons/*/build
+	$(RM) test/addons/.buildstamp test/addons/.docbuildstamp
 
 test-timers:
 	$(MAKE) --directory=tools faketime
@@ -774,9 +862,11 @@ endif
 
 .PHONY: lint cpplint jslint bench clean docopen docclean doc dist distclean \
 	check uninstall install install-includes install-bin all staticlib \
-	dynamiclib test test-all test-addons build-addons website-upload pkg \
-	blog blogclean tar binary release-only bench-http-simple bench-idle \
-	bench-all bench bench-misc bench-array bench-buffer bench-net \
-	bench-http bench-fs bench-tls cctest run-ci test-v8 test-v8-intl \
-	test-v8-benchmarks test-v8-all v8 lint-ci bench-ci jslint-ci doc-only \
-	$(TARBALL)-headers test-ci test-ci-native test-ci-js build-ci clear-stalled
+	dynamiclib test test-all test-addons test-addons-clean build-addons \
+	website-upload pkg blog blogclean tar binary release-only \
+	bench-http-simple bench-idle bench-all bench bench-misc bench-array \
+	bench-buffer bench-net bench-http bench-fs bench-tls cctest run-ci test-v8 \
+	test-v8-intl test-v8-benchmarks test-v8-all v8 lint-ci bench-ci jslint-ci \
+	doc-only $(TARBALL)-headers test-ci test-ci-native test-ci-js build-ci \
+	clear-stalled coverage-clean coverage-build coverage-test coverage \
+	list-gtests
